"""new fields in user model

Revision ID: 267d6ebad6f0
Revises: b6b5e63f78b2
Create Date: 2023-01-16 12:39:46.020065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '267d6ebad6f0'
down_revision = 'b6b5e63f78b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_seen')
        batch_op.drop_column('about_me')

    # ### end Alembic commands ###
